name: "Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  client-checks:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          working-directory: ./apps/client
          setup-tauri: "true"

      - name: Build
        working-directory: ./apps/client
        run: pnpm build

      - name: Lint (TypeScript)
        working-directory: ./apps/client
        run: pnpm lint:ts

      - name: Lint (Rust)
        working-directory: ./apps/client
        run: pnpm lint:rust
