name: "Pull Request"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  client-checks:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          working-directory: ./apps/client
          setup-tauri: "true"

      - name: Build
        working-directory: ./apps/client
        run: pnpm build

      - name: Lint
        working-directory: ./apps/client
        run: pnpm lint

  server-checks:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v6

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          working-directory: ./apps/server

      - name: Build
        working-directory: ./apps/server
        run: pnpm build

      - name: Lint
        working-directory: ./apps/server
        run: pnpm lint
